# TRIPPLE 7 MOVIE EMPIRE REVIEW

## Table of Content

### 1.Overview
### 2.Data Loading and Exploration
### 3.Data Cleaning and Preparation
### 4.Business Questions, Key Findings, and Recommendations
### 5.Conclusion

# 1. OVERVIEW

Tripple 7 movie empire is a start up company that wants to compete in the movie industry.  This analysis will help to give a general overview of the industry, to ensure the stakeholders understand how the industry works and what to expect of it, which will be ideal for decison making.

## 1.1 Business Problem

Tripple Seven plans to launch a new movie studio but lacks experience in the film industry. The company does not know which types of movies perform best at the box office or what factors contribute to a film’s financial success.

Without data-driven insights, investing in movie production could lead to poor financial outcomes. To reduce this risk, the company needs to understand how factors such as movie genre, release timing, and audience engagement affect revenue and profitability.

This project aims to analyze historical movie data to identify successful patterns and provide clear recommendations that will help Tripple Seven make informed decisions on the types of films to produce.

## 1.2 Business Understanding

Tripple 7 movie empire is a multi-billion dollar industry that has been growing rapidly in recent years due to various factors that have ensured a steady rise from the analog to digital eras.

We've witnessed improvements in distribution, quality, genres, acting, among other things.

One of the major factors has been the internet, which today is easily accessible to majority of the population worldwide. This has lead to the introduction of various streaming platforms, making it easy for viewers to download any type of movies they want to watch. Hence we have migrated from eras where we had to use compact disks(CD's/DVD's) which needed a physical store to buy them, to now using streaming platforms at the comfort of your home without needing to go out and get access to a particular movie, as long as you have internet access.

Other factors have also majorly contributed to its growth, ie,

- The use of various visual effects like CGI,VFX ensuring the movie is of high quality.
- Large investments to ensure the logistics in a movie are met and the movie is finished and distributed on time.
- Changing audience preferences ie genre preferences and cultural diversity has lead to content that caters to various audience.
- Consumer spending due to strong economy can lead to high box office revenues.
- Production and creative factors ie, script quality, acting skills, marketing and promotions can generate great revenues.

However, all industries have their own risks that can impact various aspects in production like piracy, economic downturns, budget overruns, changing audience preferences, weather-related risks, casts illness/injury, poor box-office run, among other things.Therefore it is necessary to try and mitigate all/most of these risks during the planning and production periods. One of the main ways to reduce risks is by factoring data analysis to know the current trends and target audience.

# 1.3 Objective

1. To determine the movie genres that are the most profitable.
2. To determine the best time to release a movie for maximum returns.
3. To determine whether higher-rated movies generate more revenue.

## 1.4 Business Questions

1. Which movie genres are the most profitable?
2. When is the best time to release a movie for maximum returns?
3. Do higher-rated movies generate more revenue?

## 1.5 Dataset  Dictonary

This dataset contains the following variables:
● **Unnamed**: 0: Index column created during data export (not meaningful for analysis).

● **genre_ids**: List of genre IDs associated with the movie.

● **id_x**: Movie ID from the first dataset (e.g., TMDB dataset).

● **original_language**: Original language in which the movie was produced (e.g., en).

● **original_title**: Original title of the movie.

● **popularity**: Popularity score based on user engagement and activity.

● **release_date_x**: Movie release date from the first dataset (format: YYYY-MM-DD).

● **title**: Movie title (standardized version).

● **vote_average**: Average user rating (scale of 0–10).

● **vote_count**: Total number of user votes received.

● **id_y**: Movie ID from the second dataset after merging.

● **release_date_y**: Movie release date from the second dataset (text format, e.g., Mar 26, 2010).

● **movie**: Movie title from the second dataset.

● **production_budget**: Total budget used to produce the movie (in USD, stored as a string with $).

● **domestic_gross**: Revenue generated within the domestic market (USD).

● **worldwide_gross**: Total global revenue generated by the movie (USD).

## 2. Data Loading and Exploration

 ## 2.1 Loading dataset with necessary libraries:

In [1]:
#Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 2.2 chosen Dataset

In [2]:
#relevant dataset selected
empire_1 = pd.read_csv('tmdb.movies.csv')
empire_2 = pd.read_csv('tn.movie_budgets.csv')
#give reason why we choose the 2

## 2.3 Merging two chosen Dataset

In [3]:
#merging the two dataset
merged_empire = pd.merge(
    empire_1,
    empire_2,
    left_on='original_title',
    right_on='movie',
    how='inner')
merged_empire

,Unnamed: 0,genre_ids,id_x,original_language,original_title,popularity,release_date_x,title,vote_average,vote_count,id_y,release_date_y,movie,production_budget,domestic_gross,worldwide_gross
0,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,30,"Mar 26, 2010",How to Train Your Dragon,"$165,000,000","$217,581,232","$494,870,992"
1,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,15,"May 7, 2010",Iron Man 2,"$170,000,000","$312,433,331","$621,156,389"
2,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,"$30,000,000","$191,796,233","$364,545,516"
3,2473,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,"$30,000,000","$191,796,233","$364,545,516"
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,38,"Jul 16, 2010",Inception,"$160,000,000","$292,576,195","$835,524,642"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,26323,[],509316,en,The Box,0.600,2018-03-04,The Box,8.0,1,66,"Nov 6, 2009",The Box,"$25,000,000","$15,051,977","$34,356,760"
2312,26425,[10402],509306,en,The Box,0.600,2018-03-04,The Box,6.0,1,66,"Nov 6, 2009",The Box,"$25,000,000","$15,051,977","$34,356,760"
2313,26092,"[35, 16]",546674,en,Enough,0.719,2018-03-22,Enough,8.7,3,68,"May 24, 2002",Enough,"$38,000,000","$39,177,215","$50,970,660"
2314,26322,[],513161,en,Undiscovered,0.600,2018-04-07,Undiscovered,8.0,1,7,"Aug 26, 2005",Undiscovered,"$9,000,000","$1,069,318","$1,069,318"
2315,26508,[16],514492,en,Jaws,0.600,2018-05-29,Jaws,0.0,1,41,"Jun 20, 1975",Jaws,"$12,000,000","$260,000,000","$470,700,000"

## 2.4 Previewing the data

In [4]:
merged_empire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2316 entries, 0 to 2315
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2316 non-null   int64
 1   genre_ids          2316 non-null   object
 2   id_x               2316 non-null   int64
 3   original_language  2316 non-null   object
 4   original_title     2316 non-null   object
 5   popularity         2316 non-null   float64
 6   release_date_x     2316 non-null   object
 7   title              2316 non-null   object
 8   vote_average       2316 non-null   float64
 9   vote_count         2316 non-null   int64
 10  id_y               2316 non-null   int64
 11  release_date_y     2316 non-null   object
 12  movie              2316 non-null   object
 13  production_budget  2316 non-null   object
 14  domestic_gross     2316 non-null   object
 15  worldwide_gross    2316 non-null   object
dtypes: float64(2), int64(4), object(10)
memory usage: 289.6+ KB

In [5]:
#Clean multiple columns at once
revenue_col = ['production_budget', 'domestic_gross', 'worldwide_gross']

for revenue in revenue_col:
   merged_empire[revenue] = merged_empire[revenue].str.replace('$', '', regex=False)\
                     .str.replace(',', '', regex=False)\
                     .astype(float)

In [6]:
merged_empire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2316 entries, 0 to 2315
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2316 non-null   int64
 1   genre_ids          2316 non-null   object
 2   id_x               2316 non-null   int64
 3   original_language  2316 non-null   object
 4   original_title     2316 non-null   object
 5   popularity         2316 non-null   float64
 6   release_date_x     2316 non-null   object
 7   title              2316 non-null   object
 8   vote_average       2316 non-null   float64
 9   vote_count         2316 non-null   int64
 10  id_y               2316 non-null   int64
 11  release_date_y     2316 non-null   object
 12  movie              2316 non-null   object
 13  production_budget  2316 non-null   float64
 14  domestic_gross     2316 non-null   float64
 15  worldwide_gross    2316 non-null   float64
dtypes: float64(5), int64(4), object(7)
memory usage: 289.6+ KB

In [7]:
#checking null values
merged_empire.isna().sum()

Unnamed: 0           0
genre_ids            0
id_x                 0
original_language    0
original_title       0
popularity           0
release_date_x       0
title                0
vote_average         0
vote_count           0
id_y                 0
release_date_y       0
movie                0
production_budget    0
domestic_gross       0
worldwide_gross      0
dtype: int64

In [8]:
#checking for duplicates
merged_empire.duplicated().value_counts()

False    2316
Name: count, dtype: int64

In [19]:
# Describing the dataset to get the summary statistics for the merged empire

merged_empire.describe()

,Unnamed: 0,id_x,popularity,release_date_x,vote_average,vote_count,id_y,production_budget,domestic_gross,worldwide_gross,total_profit,release_year
count,2316.000000,2316.000000,2316.000000,2316,2316.000000,2316.000000,2316.000000,2.316000e+03,2.316000e+03,2.316000e+03,2.316000e+03,2316.000000
mean,11447.636874,210410.569516,10.685747,2013-10-09 21:40:43.523315968,6.206261,1712.143351,50.842832,3.790108e+07,4.953869e+07,1.201667e+08,8.226558e+07,2013.244387
min,1.000000,62.000000,0.600000,1946-12-25 00:00:00,0.000000,1.000000,1.000000,9.000000e+03,0.000000e+00,0.000000e+00,-1.104502e+08,1946.000000
25%,5208.500000,71862.750000,5.487000,2011-12-22 12:00:00,5.600000,63.000000,27.000000,5.000000e+06,7.788272e+05,3.224914e+06,-1.743919e+06,2011.000000
50%,11160.500000,208501.500000,9.506000,2014-04-28 12:00:00,6.300000,615.000000,51.000000,1.900000e+07,2.015790e+07,3.722812e+07,1.366848e+07,2014.000000
75%,17541.250000,330641.750000,14.423750,2016-04-15 00:00:00,6.900000,2100.500000,75.000000,4.650000e+07,5.830223e+07,1.248731e+08,7.816406e+07,2016.000000
max,26508.000000,587627.000000,80.773000,2019-05-03 00:00:00,10.000000,22186.000000,100.000000,4.250000e+08,7.605076e+08,2.776345e+09,2.351345e+09,2019.000000
std,7557.377373,144548.546190,8.244311,NaN,1.178079,2704.578576,28.359866,5.150964e+07,8.261483e+07,2.218496e+08,1.834322e+08,4.713827

# 3. Data Cleaning and preparation

Purpose: To make the data clean and ready for analysis

In [11]:
# TMDb genre mapping
genre_mapping = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Science Fiction",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western"
}

# Convert genre_ids from string to list if needed
merged_empire['genre_ids'] = merged_empire['genre_ids'].apply(lambda x: eval(x) if isinstance(x, str) else x)

# Map all IDs to names
merged_empire['all_genres'] = merged_empire['genre_ids'].apply(lambda ids: [genre_mapping.get(i) for i in ids])

# Optional: Convert list to comma-separated string for readability
merged_empire['all_genres_str'] = merged_empire['all_genres'].apply(lambda x: ', '.join([g for g in x if g]))

merged_empire[['original_title', 'genre_ids', 'all_genres_str']].head(10)

,original_title,genre_ids,all_genres_str
0,How to Train Your Dragon,"[14, 12, 16, 10751]","Fantasy, Adventure, Animation, Family"
1,Iron Man 2,"[12, 28, 878]","Adventure, Action, Science Fiction"
2,Toy Story,"[16, 35, 10751]","Animation, Comedy, Family"
3,Toy Story,"[16, 35, 10751]","Animation, Comedy, Family"
4,Inception,"[28, 878, 12]","Action, Science Fiction, Adventure"
5,Percy Jackson & the Olympians: The Lightning T...,"[12, 14, 10751]","Adventure, Fantasy, Family"
6,Avatar,"[28, 12, 14, 878]","Action, Adventure, Fantasy, Science Fiction"
7,Toy Story 3,"[16, 10751, 35]","Animation, Family, Comedy"
8,Despicable Me,"[16, 10751, 35]","Animation, Family, Comedy"
9,Megamind,"[16, 28, 35, 10751, 878]","Animation, Action, Comedy, Family, Science Fic..."

In [12]:
merged_empire

,Unnamed: 0,genre_ids,id_x,original_language,original_title,popularity,release_date_x,title,vote_average,vote_count,id_y,release_date_y,movie,production_budget,domestic_gross,worldwide_gross,all_genres,all_genres_str
0,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,30,"Mar 26, 2010",How to Train Your Dragon,165000000.0,217581232.0,494870992.0,"[Fantasy, Adventure, Animation, Family]","Fantasy, Adventure, Animation, Family"
1,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,15,"May 7, 2010",Iron Man 2,170000000.0,312433331.0,621156389.0,"[Adventure, Action, Science Fiction]","Adventure, Action, Science Fiction"
2,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,30000000.0,191796233.0,364545516.0,"[Animation, Comedy, Family]","Animation, Comedy, Family"
3,2473,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,30000000.0,191796233.0,364545516.0,"[Animation, Comedy, Family]","Animation, Comedy, Family"
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,38,"Jul 16, 2010",Inception,160000000.0,292576195.0,835524642.0,"[Action, Science Fiction, Adventure]","Action, Science Fiction, Adventure"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,26323,[],509316,en,The Box,0.600,2018-03-04,The Box,8.0,1,66,"Nov 6, 2009",The Box,25000000.0,15051977.0,34356760.0,[],
2312,26425,[10402],509306,en,The Box,0.600,2018-03-04,The Box,6.0,1,66,"Nov 6, 2009",The Box,25000000.0,15051977.0,34356760.0,[Music],Music
2313,26092,"[35, 16]",546674,en,Enough,0.719,2018-03-22,Enough,8.7,3,68,"May 24, 2002",Enough,38000000.0,39177215.0,50970660.0,"[Comedy, Animation]","Comedy, Animation"
2314,26322,[],513161,en,Undiscovered,0.600,2018-04-07,Undiscovered,8.0,1,7,"Aug 26, 2005",Undiscovered,9000000.0,1069318.0,1069318.0,[],
2315,26508,[16],514492,en,Jaws,0.600,2018-05-29,Jaws,0.0,1,41,"Jun 20, 1975",Jaws,12000000.0,260000000.0,470700000.0,[Animation],Animation

In [13]:
merged_empire = merged_empire.assign(total_profit = merged_empire['worldwide_gross'] - merged_empire['production_budget'])
merged_empire

,Unnamed: 0,genre_ids,id_x,original_language,original_title,popularity,release_date_x,title,vote_average,vote_count,id_y,release_date_y,movie,production_budget,domestic_gross,worldwide_gross,all_genres,all_genres_str,total_profit
0,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,30,"Mar 26, 2010",How to Train Your Dragon,165000000.0,217581232.0,494870992.0,"[Fantasy, Adventure, Animation, Family]","Fantasy, Adventure, Animation, Family",329870992.0
1,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,15,"May 7, 2010",Iron Man 2,170000000.0,312433331.0,621156389.0,"[Adventure, Action, Science Fiction]","Adventure, Action, Science Fiction",451156389.0
2,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,30000000.0,191796233.0,364545516.0,"[Animation, Comedy, Family]","Animation, Comedy, Family",334545516.0
3,2473,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,30000000.0,191796233.0,364545516.0,"[Animation, Comedy, Family]","Animation, Comedy, Family",334545516.0
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,38,"Jul 16, 2010",Inception,160000000.0,292576195.0,835524642.0,"[Action, Science Fiction, Adventure]","Action, Science Fiction, Adventure",675524642.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,26323,[],509316,en,The Box,0.600,2018-03-04,The Box,8.0,1,66,"Nov 6, 2009",The Box,25000000.0,15051977.0,34356760.0,[],,9356760.0
2312,26425,[10402],509306,en,The Box,0.600,2018-03-04,The Box,6.0,1,66,"Nov 6, 2009",The Box,25000000.0,15051977.0,34356760.0,[Music],Music,9356760.0
2313,26092,"[35, 16]",546674,en,Enough,0.719,2018-03-22,Enough,8.7,3,68,"May 24, 2002",Enough,38000000.0,39177215.0,50970660.0,"[Comedy, Animation]","Comedy, Animation",12970660.0
2314,26322,[],513161,en,Undiscovered,0.600,2018-04-07,Undiscovered,8.0,1,7,"Aug 26, 2005",Undiscovered,9000000.0,1069318.0,1069318.0,[],,-7930682.0
2315,26508,[16],514492,en,Jaws,0.600,2018-05-29,Jaws,0.0,1,41,"Jun 20, 1975",Jaws,12000000.0,260000000.0,470700000.0,[Animation],Animation,458700000.0

In [16]:
#Creating a column of the year. 
# Make sure the date column is datetime type
# Replace 'release_date' with the name of your date column
merged_empire['release_date_x'] = pd.to_datetime(merged_empire['release_date_x'], errors='coerce')

# Extract only the year
merged_empire['release_year'] = merged_empire['release_date_x'].dt.year

# View the first few rows
merged_empire[['release_date_x', 'release_year']].head()

  release_date_x  release_year
0     2010-03-26          2010
1     2010-05-07          2010
2     1995-11-22          1995
3     1995-11-22          1995
4     2010-07-16          2010

In [17]:
merged_empire

,Unnamed: 0,genre_ids,id_x,original_language,original_title,popularity,release_date_x,title,vote_average,vote_count,id_y,release_date_y,movie,production_budget,domestic_gross,worldwide_gross,all_genres,all_genres_str,total_profit,release_year
0,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,30,"Mar 26, 2010",How to Train Your Dragon,165000000.0,217581232.0,494870992.0,"[Fantasy, Adventure, Animation, Family]","Fantasy, Adventure, Animation, Family",329870992.0,2010
1,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,15,"May 7, 2010",Iron Man 2,170000000.0,312433331.0,621156389.0,"[Adventure, Action, Science Fiction]","Adventure, Action, Science Fiction",451156389.0,2010
2,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,30000000.0,191796233.0,364545516.0,"[Animation, Comedy, Family]","Animation, Comedy, Family",334545516.0,1995
3,2473,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,37,"Nov 22, 1995",Toy Story,30000000.0,191796233.0,364545516.0,"[Animation, Comedy, Family]","Animation, Comedy, Family",334545516.0,1995
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,38,"Jul 16, 2010",Inception,160000000.0,292576195.0,835524642.0,"[Action, Science Fiction, Adventure]","Action, Science Fiction, Adventure",675524642.0,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,26323,[],509316,en,The Box,0.600,2018-03-04,The Box,8.0,1,66,"Nov 6, 2009",The Box,25000000.0,15051977.0,34356760.0,[],,9356760.0,2018
2312,26425,[10402],509306,en,The Box,0.600,2018-03-04,The Box,6.0,1,66,"Nov 6, 2009",The Box,25000000.0,15051977.0,34356760.0,[Music],Music,9356760.0,2018
2313,26092,"[35, 16]",546674,en,Enough,0.719,2018-03-22,Enough,8.7,3,68,"May 24, 2002",Enough,38000000.0,39177215.0,50970660.0,"[Comedy, Animation]","Comedy, Animation",12970660.0,2018
2314,26322,[],513161,en,Undiscovered,0.600,2018-04-07,Undiscovered,8.0,1,7,"Aug 26, 2005",Undiscovered,9000000.0,1069318.0,1069318.0,[],,-7930682.0,2018
2315,26508,[16],514492,en,Jaws,0.600,2018-05-29,Jaws,0.0,1,41,"Jun 20, 1975",Jaws,12000000.0,260000000.0,470700000.0,[Animation],Animation,458700000.0,2018